name: Deploy Next.js to GitHub Pages

on:
  push:
    branches:
      - main # Or 'master', whatever your default branch is
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20" # Use a current LTS version
          cache: 'npm'

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build
        # 'next build' will automatically run and export to 'out/'
        # because of your next.config.mjs

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out # This is the folder Next.js exports to
  
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4